### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by linkinkov** [MagicBees/MagicBees#111]
When i put magic apiary, server kick me and i have apiary stand and one in inventory:

[21:09:56] [Server thread/WARN]: Failed to handle packet for /217.66.158.54:48252
java.lang.NullPointerException
	at magicbees.tileentity.TileEntityMagicApiary.func_145841_b(TileEntityMagicApiary.java:516) ~[TileEntityMagicApiary.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState.<init>(CraftBlockState.java:49) ~[CraftBlockState.class:1.7.10-1492.152]
	at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState.getBlockState(CraftBlockState.java:87) ~[CraftBlockState.class:1.7.10-1492.152]
	at net.minecraftforge.event.world.BlockEvent$PlaceEvent.<init>(BlockEvent.java:150) ~[BlockEvent$PlaceEvent.class:1.7.10-1492.152]
	at net.minecraftforge.event.world.BlockEvent$MultiPlaceEvent.<init>(BlockEvent.java:178) ~[BlockEvent$MultiPlaceEvent.class:1.7.10-1492.152]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerMultiBlockPlace(ForgeEventFactory.java:59) ~[ForgeEventFactory.class:1.7.10-1492.152]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:593) ~[ForgeHooks.class:1.7.10-1492.152]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:152) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:495) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
[21:09:56] [Server thread/INFO]: linkinkov lost connection: Internal server error
[21:09:56] [Server thread/ERROR]: A TileEntity type magicbees.tileentity.TileEntityMagicApiary has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
	at magicbees.tileentity.TileEntityMagicApiary.func_145841_b(TileEntityMagicApiary.java:516) ~[TileEntityMagicApiary.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:391) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:358) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:503) [ms.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:261) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by MysteriousAges** [comment]
Can you reproduce this on a server that does not run CraftBukkit? It changes too much underlying code for me to be able to reproduce crashes and determine a cause and therefore a fix reliably.
