### ISSUE TITLE
bottlerManager

### ISSUE THREAD

**Issue by mezz** [MagicBees/MagicBees#16]
Hi there Arkanos, I got this crash on startup right after initialization. Something about bottlerManager. Using Forge 1208.

Crash Report:

Time: 9/22/14 11:25 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: bottlerManager
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: bottlerManager
	at magicbees.main.utils.CraftingManager.registerLiquidContainer(CraftingManager.java:645)
	at magicbees.main.utils.CraftingManager.registerLiquidContainers(CraftingManager.java:27)
	at magicbees.main.MagicBees.postInit(MagicBees.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more

**Comment by mezz** [comment]
_From Jermaine Garcia on 2014-09-22 18:35:21+00:00_

Forgot to mention that I'm also using the latest MagicBees build magicbees-1.7.10-2.1.20.jar. Forestry version: forestry_1.7.10-3.0.0.174.jar.

**Comment by mezz** [comment]
_From [Arkandos](http://bitbucket.org/Arkandos) on 2014-09-22 18:40:17+00:00_

Oh god. Please use pastebin and I'll look into this

**Comment by mezz** [comment]
_From Jermaine Garcia on 2014-09-22 18:42:03+00:00_

Oh right sorry. I'm actually getting the same error from 2.1.19 as well. So it must be a conflict with another mod. I'm looking into it right now.

**Comment by mezz** [comment]
_From Jermaine Garcia on 2014-09-22 19:19:40+00:00_

Heads up. It's Forestry. Trying to find which Forestry build version is not working with MB.

**Comment by mezz** [comment]
_From Jermaine Garcia on 2014-09-22 20:49:19+00:00_

I think I found it. [Forestry Build #172](http://ic2api.player.to:8080/job/Forestry/172/) "Fixed Bottler, removed fuelcan recipe from IC2 since it no longer exists." 

Here is my crash report: [Pastebin](http://pastebin.com/JzLfGg35)

**Comment by mezz** [comment]
_From [Arkandos](http://bitbucket.org/Arkandos) on 2014-09-22 20:53:49+00:00_

I'll see what I can do
No wonder I had missed that, it was uploaded yesterday

**Comment by mezz** [comment]
_From [Arkandos](http://bitbucket.org/Arkandos) on 2014-09-22 20:58:17+00:00_

Question: In Forestry 172, is there no bottler?
Edit: Try if this build works https://dl.dropboxusercontent.com/u/37675952/magicbees-1.7.10-2.1.20-dev.jar

**Comment by mezz** [comment]
_From Jermaine Garcia on 2014-09-22 21:01:43+00:00_

That would be my guess. But according to the Changelog, it sounds like they just removed the fuelcan recipe. The crash error states that the bottleManager "field" doesn't exist. Not sure if it's a Forestry side error or MagicBees error.

If it's a Forestry Error, then I could make a bug report over there.

**Comment by mezz** [comment]
_From [Arkandos](http://bitbucket.org/Arkandos) on 2014-09-22 21:07:11+00:00_

Not a forestry error. They changed something in the API, which happens quite often now.
Have you tried the build I linked?

**Comment by mezz** [comment]
_From Jermaine Garcia on 2014-09-22 21:07:50+00:00_

Oh no let me try that one.

**Comment by mezz** [comment]
_From Jermaine Garcia on 2014-09-22 21:25:41+00:00_

You go it! It loaded in.

**Comment by mezz** [comment]
_From [Arkandos](http://bitbucket.org/Arkandos) on 2014-09-22 21:26:36+00:00_

Good. Then I'm closing this
