### ISSUE TITLE
NPE Crash on exception: Ticking Player

### ISSUE THREAD

**Issue by SethWilliamson** [MagicBees/MagicBees#47]
Game crashes shortly after loading world. No player action; just standing idle.

magicbees-1.7.10-2.3.0
Botania r1.6-183

```
[16:57:59] [Server thread/ERROR]: 67: ASM: vazkii.botania.common.item.ItemRegenIvy@7d60d7d8 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[16:57:59] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
	at cpw.mods.fml.common.eventhandler.EventBus.unregister(EventBus.java:124) ~[EventBus.class:?]
	at magicbees.main.utils.TickHandlerVersion.unsubscribeFromBus(TickHandlerVersion.java:81) ~[TickHandlerVersion.class:?]
	at magicbees.main.utils.TickHandlerVersion.tickStart(TickHandlerVersion.java:51) ~[TickHandlerVersion.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1950_TickHandlerVersion_tickStart_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more
```

Full log: http://slexy.org/raw/s21Y7mzXqA (expires 2015-10-21)

**Comment by MysteriousAges** [comment]
Might be mod interaction; the TickHandlerVersion class did not change between 2.2.3 and 2.3.0-beta. |:

**Comment by SynfulChaot** [comment]
I've confirmed that it's still causing crashes, even with 2.3.1, but it isn't doing it in a 'pure' environment with only Magic Bees, Forestry, Botania, and Baubles.  I'm still working on determining the mod that's causing the crashes.
