### ISSUE TITLE
latest jar is deobf, crashes with NoSuchFieldError: dirt

### ISSUE THREAD

**Issue by radebrecht** [MagicBees/MagicBees#52]
magicbees-1.7.10-2.3.0-deobf.jar

```
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: dirt
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: dirt
	at magicbees.bees.HiveDescription.<clinit>(HiveDescription.java:32)
	at magicbees.main.utils.compat.ForestryHelper.preInit(ForestryHelper.java:112)
	at magicbees.main.utils.compat.ModHelper.preInit(ModHelper.java:7)
	at magicbees.main.MagicBees.preInit(MagicBees.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more
```

**Comment by MysteriousAges** [comment]
I think maybe you grabbed the dev version, rather than the public release.

**Comment by radebrecht** [comment]
That's probably it, the point being that I got the file from your
curseforge entry
http://minecraft.curseforge.com/mc-mods/65764-magic-bees/files/2235782
 Maybe there's been some mistake while copying it there?

On 29 April 2015 at 20:32, MysteriousAges <notifications@github.com> wrote:

> I think maybe you grabbed the dev version, rather than the public release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MagicBees/MagicBees/issues/52#issuecomment-97534154>.
>



-- 
Ben Schlingelhof
benseins.de

**Comment by radebrecht** [comment]
Oh yes, now I see. The file I downloaded is listed unter "additional
files", whereas the release file is the actual download button. I'm deeply
embarrassed, apologies

On 29 April 2015 at 20:57, Ben Schlingelhof <ben@benseins.de> wrote:

> That's probably it, the point being that I got the file from your
> curseforge entry
> http://minecraft.curseforge.com/mc-mods/65764-magic-bees/files/2235782
>  Maybe there's been some mistake while copying it there?
>
> On 29 April 2015 at 20:32, MysteriousAges <notifications@github.com>
> wrote:
>
>> I think maybe you grabbed the dev version, rather than the public release.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MagicBees/MagicBees/issues/52#issuecomment-97534154>.
>>
>
>
>
> --
> Ben Schlingelhof
> benseins.de
>



-- 
Ben Schlingelhof
benseins.de

**Comment by MysteriousAges** [comment]
No worries.
