### ISSUE TITLE
Ticking block entity server crash

### ISSUE THREAD

**Issue by CrowAU** [MagicBees/MagicBees#58]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 05/05/15 00:28
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at magicbees.bees.allele.flowerProvider.FlowerProviderArsMagicaFlower.growFlower(FlowerProviderArsMagicaFlower.java:43)
	at forestry.apiculture.genetics.Bee.plantFlowerRandom(Bee.java:761)
	at forestry.apiculture.BeekeepingLogic.doQueenWorkCycle(BeekeepingLogic.java:149)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:140)
	at forestry.apiculture.BeekeepingLogic.update(BeekeepingLogic.java:125)
	at forestry.apiculture.gadgets.TileBeehouse.updateServerSide(TileBeehouse.java:175)
	at forestry.core.gadgets.TileBase.func_145845_h(TileBase.java:39)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at magicbees.bees.allele.flowerProvider.FlowerProviderArsMagicaFlower.growFlower(FlowerProviderArsMagicaFlower.java:43)
	at forestry.apiculture.genetics.Bee.plantFlowerRandom(Bee.java:761)
	at forestry.apiculture.BeekeepingLogic.doQueenWorkCycle(BeekeepingLogic.java:149)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:140)
	at forestry.apiculture.BeekeepingLogic.update(BeekeepingLogic.java:125)
	at forestry.apiculture.gadgets.TileBeehouse.updateServerSide(TileBeehouse.java:175)
	at forestry.core.gadgets.TileBase.func_145845_h(TileBase.java:39)

-- Block entity being ticked --
Details:
	Name: forestry.Apiary // forestry.apiculture.gadgets.TileApiary
	Block type: ID #1006 (tile.for.apiculture // forestry.core.gadgets.BlockBase)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-9,63,534), Chunk: (at 7,3,6 in -1,33; contains blocks -16,0,528 to -1,255,543), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Actual block type: ID #1006 (tile.for.apiculture // forestry.core.gadgets.BlockBase)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['_Crow_'/1835, l='world', x=-10.77, y=63.00, z=548.75]]
	Chunk stats: ServerChunkCache: 838 Drop: 0
	Level seed: -576803013844025314
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-226,64,564), Chunk: (at 14,4,4 in -15,35; contains blocks -240,0,560 to -225,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 50605726 game time, 67538108 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 171644 (now: false), thunder time: 134212 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by CrowAU** [comment]
After some testing I can replicate the crash by putting terrestic bees into a hive with cerublossom from ars magica 2 nearby and letting the queen be remade on the first cycle using item pipes to place the queen back into the hive again.

**Comment by MysteriousAges** [comment]
I suspect my AM2 integration has fallen out of date again. Will have to update it if they've renamed blocks.

**Comment by Tukanen** [comment]
If it helps narrow the problem down, I can tell you that cerublossom works just fine, however the bees don't react when I plant Aums near them, nor do they ever create any. (However the server do crash from time to time with the same crashlog as the OP)

PS. I have laid out patches of sand and stone to test for desert nova and tarma root.

**Comment by MysteriousAges** [comment]
@CrowAU It would be helpful if you could provide me with version numbers. I'm looking at the latest 1.7 build of AM2 from Mithion, and can't see anything that might be wrong.
