### ISSUE TITLE
Crash when the Magic Apiary is placed

### ISSUE THREAD

**Issue by siriulx** [MagicBees/MagicBees#66]
Forge: 1403
Magic Bees: 2.3.1
Forestry: 3.6.0.578 unstable

Crash Report:
java.lang.NoSuchMethodError: forestry.core.utils.Utils.getBiomeAt(Lnet/minecraft/world/World;II)Lnet/minecraft/world/biome/BiomeGenBase;
	at magicbees.tileentity.TileEntityMagicApiary.updateBiome(TileEntityMagicApiary.java:572)
	at magicbees.tileentity.TileEntityMagicApiary.func_145845_h(TileEntityMagicApiary.java:558)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:123)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at magicbees.tileentity.TileEntityMagicApiary.updateBiome(TileEntityMagicApiary.java:572)
	at magicbees.tileentity.TileEntityMagicApiary.func_145845_h(TileEntityMagicApiary.java:558)

-- Block entity being ticked --
Details:
	Name: magicbees.magicApiary // magicbees.tileentity.TileEntityMagicApiary
	Block type: ID #745 (tile.magicApiary // magicbees.block.BlockMagicApiary)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-5,68,5), Chunk: (at 11,4,5 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #745 (tile.magicApiary // magicbees.block.BlockMagicApiary)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

**Comment by marcin212** [comment]
http://hastebin.com/redeweduda.avrasm

**Comment by MysteriousAges** [comment]
Referenced an internal Forestry method. oops.
Closed by 8ef17ec
