### ISSUE TITLE
Biome/Magic Apiary Crash

### ISSUE THREAD

**Issue by SalmonSays** [MagicBees/MagicBees#77]
Description: Ticking block entity
java.lang.NoSuchMethodError: forestry.core.utils.Utils.getBiomeAt(Lnet/minecraft/world/World;II)Lnet/minecraft/world/biome/BiomeGenBase;
	at magicbees.tileentity.TileEntityMagicApiary.updateBiome(TileEntityMagicApiary.java:572)
	at magicbees.tileentity.TileEntityMagicApiary.func_145845_h(TileEntityMagicApiary.java:558)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

This occured as soon as I placed down a magic apiary on a test creative world after updating to Latest Forestry 3.6.2

**Comment by MysteriousAges** [comment]
Yeah, I accidentally left some refs to Forestry internals in the last build.
Resolved in e0432846d59ba42ba5dc9dd704af6fc870b2b6aa
