### ISSUE TITLE
NPE with some recipes.

### ISSUE THREAD

**Issue by anishin** [MagicBees/MagicBees#85]
Hello.
I'm getting NPE when try to dump all bee mutations. I get empty 'bee_mutation.csv' file and this message in log:
```
[Client thread/ERROR] [NotEnoughItems/]: Error dumping Bee Mutations mode: 0
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at magicbees.bees.BeeMutation.getSpecialConditions(BeeMutation.java:538) ~[BeeMutation.class:?]
	at net.bdew.neiaddons.forestry.MutationDumper.dump(MutationDumper.scala:35) ~[MutationDumper.class:?]
	at net.bdew.neiaddons.forestry.MutationDumper.dump(MutationDumper.scala:18) ~[MutationDumper.class:?]
	at codechicken.nei.config.ArrayDumper.dump(ArrayDumper.java:22) ~[ArrayDumper.class:?]
	at codechicken.nei.config.DataDumper.dumpTo(DataDumper.java:66) ~[DataDumper.class:?]
	at codechicken.nei.config.DataDumper.dumpFile(DataDumper.java:41) [DataDumper.class:?]
	at codechicken.nei.config.DataDumper.mouseClicked(DataDumper.java:141) [DataDumper.class:?]
	at codechicken.nei.config.GuiOptionList$OptionScrollSlot.slotClicked(GuiOptionList.java:129) [GuiOptionList$OptionScrollSlot.class:?]
	at codechicken.core.gui.GuiScrollSlot.slotUp(GuiScrollSlot.java:129) [GuiScrollSlot.class:?]
	at codechicken.core.gui.GuiScrollPane.mouseMovedOrUp(GuiScrollPane.java:143) [GuiScrollPane.class:?]
	at codechicken.core.gui.GuiScreenWidget.func_146286_b(GuiScreenWidget.java:96) [GuiScreenWidget.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) [bdw.class:?]
	at codechicken.core.gui.GuiScreenWidget.func_146274_d(GuiScreenWidget.java:127) [GuiScreenWidget.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

Also I'm getting crash sometimes with the same message, when try to see bee mutations in NEI.
Please, fix this problem! Version of MagicBees - 2.3.3.
If it's problem of NEI Addons - please, report it to @bdew.

P. S. Sorry for my English. I'm from Russia.

**Comment by anishin** [comment]
Bees from BloodMagic cause this issue. Without BloodMagic I haven't this problem.

**Comment by bdew** [comment]
Added a workaround for crashes in getSpecialConditions in NEI Addons 1.12.12

**Comment by MysteriousAges** [comment]
Blood Magic bees have been removed in the latest version because they don't do anything.
