### ISSUE TITLE
Game crash: magicbees.bees.BeeMutation

### ISSUE THREAD

**Issue by Protheus** [MagicBees/MagicBees#98]
using: 
- Forestry_1.7.10-4.0.0.690-unstable
- Magicbees-1.7.10-2.3.4
- Magicbees-1.7.10-2.3.5

I'm not sure if magic bees is compatible with forestry unstable or if this is forestry error and not magic bees.

Getting a game crashes on loading with the following error: http://pastebin.com/JNzficHJ

cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.AbstractMethodError
	at forestry.apiculture.genetics.BeeHelper.registerMutation(BeeHelper.java:244)
	at magicbees.bees.BeeMutation.<init>(BeeMutation.java:391)
	at magicbees.bees.BeeMutation.setupMutations(BeeMutation.java:48)
	at magicbees.bees.BeeManager.lateBeeInit(BeeManager.java:41)
	at magicbees.main.MagicBees.postInit(MagicBees.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more

**Comment by mezz** [comment]
That's a pretty weird crash, `BeeHelper.registerMutation` hasn't changed in any version of Forestry so I'm not sure why it would crash here.

**Comment by Protheus** [comment]
Also tried the 699 of FU and got the same result. Guess it is not working with the FU version. Have not tried the stable version yet

**Comment by Protheus** [comment]
Tried it again with the new FU 705 but the same error. Posted an issue on forestry also. https://github.com/ForestryMC/ForestryMC/issues/839

**Comment by Protheus** [comment]
All is working in the normal versions, so not compatible with FU yet - hope it will be soon ;-)

**Comment by mezz** [comment]
I just fixed this issue in Forestry, Magic Bees should work fine with Forestry 4.0 now.

**Comment by Protheus** [comment]
Sweet thank you

**Comment by DevStark22** [comment]
Hi !
For 2019 users which have the same issue, try removing RedstoneArsenal, for me it work just fine. 😄
